routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Api\ShippingConfiguration\Box\BoxController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('login', [HomeController::class, 'index']);
Route::get('/', function(){
    return view('home');
})->middleware('auth');

Auth::routes();

Route::middleware(['auth'])->group(function () {

    Route::get('/shippings-config-user','ShippingConfigController@shippingsConfigUser');

    Route::resource('/shippings-config','ShippingConfigController')->only(['index','store','update','destroy']);
    //Route::resource('configurations', 'ConfigurationController',['only' => ['update','index']]);

    /*
    * Configuration Special Prices Routes
    */
    Route::name('special_prices.')->group(function () {
        Route::get('/special_prices', [App\Http\Controllers\SpecialPricesController::class, 'index'])->name('index');
        Route::post('/special_prices/show', [App\Http\Controllers\SpecialPricesController::class, 'show'])->name('show');
        Route::post('/special_prices/store', [App\Http\Controllers\SpecialPricesController::class, 'store'])->name('store');
        Route::get('/special_prices/create', [App\Http\Controllers\SpecialPricesController::class, 'create'])->name('create');
        Route::post('/special_prices/delete', [App\Http\Controllers\SpecialPricesController::class, 'delete'])->name('delete');
        Route::post('/special_prices/destroy', [App\Http\Controllers\SpecialPricesController::class, 'destroy'])->name('destroy');
        Route::post('/special_prices/search', [App\Http\Controllers\SpecialPricesController::class, 'searchProducts'])->name('search');
    });

    /*Base prices Routes
    *
    */
    Route::name('base-prices.')->group(function () {
        Route::get('/base-prices', [App\Http\Controllers\BasePriceController::class, 'index'])->name('index');
    });

    Route::resource('rules-configurator', 'RuleConfiguratorController', [
        'parameters' => [
            'rules-configurator' => 'rule'
        ],
        'except' => [
            'show'
        ]
    ]);

    Route::resource('global-costs-configurator', 'GlobalCostConfiguratorController', [
        'parameters' => [
            'global-costs-configurator' => 'cost'
        ],
        'except' => [
            'show'
        ]
    ]);

    Route::resource('global-utility', 'GlobalUtilityController', [
        'parameters' => [
            'global-utility' => 'cost'
        ],
        'only' => [
            'index',
            'update'
        ]
    ]);
    
    
    Route::resource('box', 'BoxController', [
        'except' => [
            'show'
        ]
    ]);

    Route::resource('products', 'ProductController', [
        'except' => [
            'index'
        ]
    ]);

});


Route::get('{any}', [HomeController::class, 'index'])->where('any', '.*');

app/Http/Controllers/BasePriceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\Facades\DataTables as DT;

class BasePriceController extends Controller
{
    /**
     * Display a listing of the base prices.
     * @author daniel.cruz@losfra.dev
     * @created 2021-01-08
     * @return mixed
     */
    public function index()
    {
        $basePrices = DB::connection('medicadepot')->select('SET NOCOUNT ON ; EXEC SP_Costos_Emp');
        $attributes = array_keys((array)$basePrices[0]);
        foreach ($basePrices as $price => $value) {
            foreach ($value as $v => $z) {
                if (is_numeric($z)) {
                    $value->$v = number_format((float)$z, 2, '.', '');                    
                }
            }
        }

        if (request()->ajax() or request()->expectsJson()) {
            return DT::of($basePrices)
            ->addColumn('actions', function ($basePrice) {
                return view('base_prices.partials.buttons', ['basePrice' => $basePrice]);
            })
            ->rawColumns(['actions'])
            ->make(true);
        }
        return view('base_prices.index')->with('attributes', $attributes);
    }
}

resources/views/base_prices/index.blade.php
@extends('adminlte::page')

@section('title', 'Precios')

@section('content_header')
    @component('components.breadcrumb', [
        'current' => 'Costo base emprendedores'
    ])
    @endcomponent
@stop

@section('content')
@if (session()->has('message'))
    <div class="alert-success" id="popup_notification">
        <strong>{{ session('message') }}</strong>
    </div>
@endif
    <div id="accordion">
        <div class="card animated bounceInDown">
            <div class="card-header">
                <h5 class="mb-0">
                    <a class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Listado
                    </a>
                </h5>
            </div>

            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="card-body table-responsive">
                    <table class="table" id="myTable">
                        <thead>
                        <tr>
                            @foreach ($attributes as $attr)
                                <th>{{$attr}}</th>
                            @endforeach                            
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
            
        </div>
    </div>

    @includeIf('base_prices.partials.show')
@stop

@push('js')
    <script>
        $(function () {
            _index.datatable();
        });

        const _index = {
            datatable: function () {
                var resultAttributes = {!! json_encode($attributes) !!};

                var atttributes = [];
                resultAttributes.forEach(element => {
                 atttributes.push({data: element, name: element});
                });
                
                $('#myTable').DataTable({
                    processing: true,
                    serverSide: true,
                    language:{
                        url: "{{ asset('/js/Spanish.json') }}"
                    },
                    ajax: "{{ route('base-prices.index') }}",
                    columns: atttributes
                });
            },
            fillMdl: function (that) {
                let data = JSON.parse(that.dataset['price']);
                $('#rows-div').empty();
                $.each(data, (idx, val) => {
                    $('#rows-div').append('<div class="form-group col-md-6 col-sm-12"><span class="font-weight-bold">' + idx + '</span>: ' + val + '</div>');
                });
            }
        }

        
    </script>
@endpush