routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Api\ShippingConfiguration\Box\BoxController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('login', [HomeController::class, 'index']);
Route::get('/', function(){
    return view('home');
})->middleware('auth');

Auth::routes();

Route::middleware(['auth'])->group(function () {

    Route::get('/shippings-config-user','ShippingConfigController@shippingsConfigUser');

    Route::resource('/shippings-config','ShippingConfigController')->only(['index','store','update','destroy']);
    //Route::resource('configurations', 'ConfigurationController',['only' => ['update','index']]);

    /*
    * Configuration Special Prices Routes
    */
    Route::name('special_prices.')->group(function () {
        Route::get('/special_prices', [App\Http\Controllers\SpecialPricesController::class, 'index'])->name('index');
        Route::post('/special_prices/show', [App\Http\Controllers\SpecialPricesController::class, 'show'])->name('show');
        Route::post('/special_prices/store', [App\Http\Controllers\SpecialPricesController::class, 'store'])->name('store');
        Route::get('/special_prices/create', [App\Http\Controllers\SpecialPricesController::class, 'create'])->name('create');
        Route::post('/special_prices/delete', [App\Http\Controllers\SpecialPricesController::class, 'delete'])->name('delete');
        Route::post('/special_prices/destroy', [App\Http\Controllers\SpecialPricesController::class, 'destroy'])->name('destroy');
        Route::post('/special_prices/search', [App\Http\Controllers\SpecialPricesController::class, 'searchProducts'])->name('search');
    });

    /*Base prices Routes
    *
    */
    Route::name('base-prices.')->group(function () {
        Route::get('/base-prices', [App\Http\Controllers\BasePriceController::class, 'index'])->name('index');
    });

    Route::resource('rules-configurator', 'RuleConfiguratorController', [
        'parameters' => [
            'rules-configurator' => 'rule'
        ],
        'except' => [
            'show'
        ]
    ]);

    Route::resource('global-costs-configurator', 'GlobalCostConfiguratorController', [
        'parameters' => [
            'global-costs-configurator' => 'cost'
        ],
        'except' => [
            'show'
        ]
    ]);

    Route::resource('global-utility', 'GlobalUtilityController', [
        'parameters' => [
            'global-utility' => 'cost'
        ],
        'only' => [
            'index',
            'update'
        ]
    ]);
    
    
    Route::resource('box', 'BoxController', [
        'except' => [
            'show'
        ]
    ]);

    Route::resource('products', 'ProductController', [
        'except' => [
            'index'
        ]
    ]);

});


Route::get('{any}', [HomeController::class, 'index'])->where('any', '.*');

app/Http/Controllers/Api/ProductConfiguration/Product/ProductController.php
<?php

namespace App\Http\Controllers\Api\ProductConfiguration\Product;

use App\Rack;
use App\Nivel;
use App\Product;
use Illuminate\Http\Request;
use App\Traits\ApiResponserTrait;
use App\Models\MedicaDepot\Profit;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use App\Http\Controllers\Controller;
use App\Http\Requests\ProductConfiguration\ProductRequest;

class ProductController extends Controller
{
  use ApiResponserTrait;
    /**
     * Display a listing of the resource.
     * @auth José Vega <jose.vega@nuvem.mx>
     * @date 2021-03-26
     * @updated 2020/06/22 Noe Reyes <noe.reyes@nuvem.mx>
     * @param
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::active()->with('images', 'profit', 'locations.seccion.nivel.rack')
            ->paginate(50);
        return response()->json(compact('products'));

    }

    /**
     * Retrieves data to fill rack select options on location form
     *
     * @author Giovanny González <giovanny.gonzalez@nuvem.mx>
     * created 14/06/2021
     * @params
     * @return Illuminate\Http\JsonResponse
     *
     */
    public function getRackSelectsOptions()
    {
      try {
        $racks = Rack::all();
        return $this->successResponse($racks, 200);
      } catch (\Exception $e) {
        Log::error($e);
        return $this->errorResponse($e->getMessage(), 500);
      }
    }
    /**
     * Retrieves data to fill nivel select options on location form
     *
     * @author Giovanny González <giovanny.gonzalez@nuvem.mx>
     * created 14/06/2021
     * @params App\Rack $rack
     * @return Illuminate\Http\JsonResponse
     *
     */
    public function getNivelSelectsOptions(Rack $rack)
    {
      try {
        $niveles = $rack->niveles;
        return $this->successResponse($niveles, 200);
      } catch (\Exception $e) {
        Log::error($e);
        return $this->errorResponse($e->getMessage(), 500);
      }
    }
    /**
     * Retrieves data to fill seccion select options on location form
     *
     * @author Giovanny González <giovanny.gonzalez@nuvem.mx>
     * created 14/06/2021
     * @params App\Rack $rack
     * @return Illuminate\Http\JsonResponse
     *
     */
    public function getSeccionSelectsOptions(Nivel $nivel)
    {
      try {
        $secciones = $nivel->secciones;
        return $this->successResponse($secciones, 200);
      } catch (\Exception $e) {
        Log::error($e);
        return $this->errorResponse($e->getMessage(), 500);
      }
    }

    /**
     * Store a newly created resource in storage.
     * @auth José Vega <jose.vega@nuvem.mx>
     * @date 2021-03-26
     * @param  \Illuminate\Http\ProductRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        try {
            $object = json_decode($request->newProduct);

            $existentIdProd1 = Product::find($object->Id_Prod1);
            if($existentIdProd1)
                return response(['message' => 'La clave nemotécnica ya existe, escriba una diferente.'], 400);
            $existentIdProd3 = Product::where('Id_Prod3', $object->Id_Prod3)->first();
            if($existentIdProd3)
                return response(['message' => 'La clave licitación ya existe, escriba una diferente.'], 400);

            $data = json_decode(json_encode($object), true);
            $product = Product::create($data);

            if($request->exists('images'))
                $product->saveImages($data['Id_Prod1'] ,$request->images, 'products');
            if(!empty($object->locations));
                $product->saveLocations($object->Id_Prod1, $object->locations);

            return response(['message' => 'Created successfully']);
        } catch (\Exception $e) {
            Log::error($e);
            return response([$e], 500);
        }
    }

    /**
     * Update the specified resource in storage.
     * @auth José Vega <jose.vega@nuvem.mx>
     * @date 2021-04-16
     * @param  \Illuminate\Http\Request  $request
     * @param  Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        try {
            $object = json_decode($request->newProduct);
            $data = json_decode(json_encode($object), true);
            $product->update($data);
            if($request->exists('images')){
                $product->updateImages($data['Id_Prod1'] ,$request->images, 'products');
            }
            if(!empty($object->locations));
                $product->saveLocations($object->Id_Prod1, $object->locations);

            return response(['message' => 'Updated successfully']);
        } catch (\Exception $e) {
            Log::error($e);
            return response([$e], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     * @auth José Vega <jose.vega@nuvem.mx>
     * @date 2021-04-16
     * @param  RuleSpecialCost $rule
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->toggleStatus();
        return response()->json(['product' => $product->refresh()]);
    }

    /**
     * Store a newly created resource in storage.
     * @auth José Vega <jose.vega@nuvem.mx>
     * @date 2021-04-19
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Http\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function storeProfit(Request $request, Product $product)
    {
        try {
            $profit = new Profit;
            $profit->Utilidad = $request->newProductProfit;
            $profit->Id_Prod1 = $product->Id_Prod1;
            $product->profit()->save($profit);
            return response(['message' => $request->all()]);
        } catch (\Exception $e) {
            Log::error($e);
            return response([$e], 500);
        }
    }

    /**
     * Update a profit.
     * @auth José Vega <jose.vega@nuvem.mx>
     * @date 2021-04-19
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Http\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function updateProfit(Request $request, Product $product)
    {
        try {
            $product->profit()->update(['Utilidad'=> $request->newProductProfit]);
            return response(['message' => $request->all()]);
        } catch (\Exception $e) {
            Log::error($e);
            return response([$e], 500);
        }
    }

    /**
     * Search for a specific product.
     * @auth José Vega <jose.vega@nuvem.mx>
     * @date 2021-04-19
     * @updated Oscar Castellanos <oscar.castellanos@nuvem.mx> 11/06/2021
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function searchProduct(Request $request){
        $products =  Product::active()->where('Descrip1', 'LIKE', "%$request->search%")->paginate(50);
        $products=$products->merge(Product::active()->where('Id_Prod3', 'LIKE', "%$request->search%")->paginate(50));
        $products=$products->merge(Product::active()->where('Id_Prod1', 'LIKE', "%$request->search%")->paginate(50));
        return response()->json(compact('products'));
    }

    /**
     * Filter products.
     * @auth Oscar Castellanos <oscar.castellanos@nuvem.mx>
     * @date 2021-06-11
     * @updated 2020/06/22 Noe Reyes <noe.reyes@nuvem.mx>
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function filterProduct(Request $request){
        if ($request->filter == "E-commerce") {
            $products = Product::ecommerce();
        } elseif ($request->filter == "Sin codigo de barras") {
            $products = Product::noBarcode();
        } else {
            $products = Product::query();
        }

        $products = $products->active()->with('images', 'profit')->paginate(50);
        return response()->json(compact('products'));
    }
       /**
     * search the products in the database.
     * @auth
     * @date
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function searchProducts(Request $request)
    {
        $product = new Product();
        $products = $product->searchProducts($request);
        return response()->json(compact('products'));
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(request()->ajax())
            return Product::datatable();
        return view('products.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Store/ProductController.php
<?php

namespace App\Http\Controllers\Store;

use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = DB::connection('medicadepot')
            ->table('vArticulosCosEco')->where('ID_PROD1', $id)->first();
        return view('store.product', ['product' => $product]);

    }

}

resources/views/products/partials/buttons.blade.php
@permission('*article')
<div class="btn-group dropleft">
    <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Opciones
    </button>
    <div class="dropdown-menu">
        @permission('list_article')
            <a class="dropdown-item" data-rule="{{ json_encode($product) }}" onclick="window.fillMdl(this)" href="#"
               data-toggle="modal" data-target="#show-modal">
                Detalles
            </a>
        @endpermission
        @permission('edit_article')
            <a href="{{ route('rules-configurator.edit', $product->Id_Prod1) }}" class="dropdown-item">
                Editar
            </a>
        @endpermission
        @permission('delete_article')
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" onclick="_global.toggleStatus('{{ route('rules-configurator.destroy', $product->Id_Prod1) }}')" href="#">
                Cambiar estatus
            </a>
        @endpermission
    </div>
</div>
@endpermission

resources/views/products/partials/classificationForm.blade.php
    @includeIf('alerts.errors')
    {{ Form::open(['route' => 'rules-configurator.store', 'method' => 'POST', 'class' => 'animated bounceInDown']) }}    
        <div class="form-row">
            <div class="col-4">
                {{ Form::label('supplier1', 'Categoría', ['class' => '']) }}
                {{ Form::select('category', array('L' => 'Large', 'S' => 'Small'), null, ['class' => 'form-control form-control-sm', 'required']) }}
            </div>
            <div class="col-4">
                {{ Form::label('supplier2', 'Familia', ['class' => '']) }}
                {{ Form::select('supplier2', array('L' => 'Large', 'S' => 'Small'), null, ['class' => 'form-control form-control-sm', 'required']) }}
            </div>
            <div class="col-4">
                {{ Form::label('supplier2', 'Marca', ['class' => '']) }}
                {{ Form::select('supplier2', array('L' => 'Large', 'S' => 'Small'), null, ['class' => 'form-control form-control-sm', 'required']) }}
            </div>
        </div>

        <div class="form-row">
            <div class="col-4">
                {{ Form::label('supplier1', 'Especialidad', ['class' => '']) }}
                {{ Form::select('supplier1', array('L' => 'Large', 'S' => 'Small'), null, ['class' => 'form-control form-control-sm', 'required']) }}
            </div>
            <div class="col-4">
                {{ Form::label('supplier2', 'Estatus', ['class' => '']) }}
                {{ Form::select('supplier2', array('L' => 'Large', 'S' => 'Small'), null, ['class' => 'form-control form-control-sm', 'required']) }}
            </div>
            <div class="col-4">
                {{ Form::label('supplier2', 'Origen', ['class' => '']) }}
                {{ Form::select('supplier2', array('L' => 'Large', 'S' => 'Small'), null, ['class' => 'form-control form-control-sm', 'required']) }}
            </div>
        </div>
        
        <div class="mt-3 mb-3" style="text-align: center">
            <button type="submit" class="btn btn-success btn-flat">
                <i class="fas fa-save"></i> Guardar
            </button>
            <a class="btn btn-danger btn-flat" href="{{ url()->route('rules-configurator.index') }}">
                <i class="fas fa-ban"></i> Cancelar
            </a>
        </div>
    {{ Form::close() }}

resources/views/products/partials/generalForm.blade.php
    @includeIf('alerts.errors')
    <h4><b>Alta del Producto</b></h4>
    {{ Form::open(['route' => 'rules-configurator.store', 'method' => 'POST', 'class' => 'animated bounceInDown']) }}    
        <div class="form-row">
            <div class="col-3">
                {{ Form::label('Clave Nemotécnica', 'Clave Nemotécnica', ['class' => '']) }}
                {{ Form::text('Descripcion', null, ['class' => 'form-control form-control-sm', 'required', 'placeholder'=>'Ingresa la clave nemotécnica', 'maxlength' => '80']) }}
            </div>
            <div class="col-3">
                {{ Form::label('Descripcion', 'Clave Licitación', ['class' => '']) }}
                {{ Form::text('Descripcion', null, ['class' => 'form-control form-control-sm', 'required', 'placeholder'=>'Ingresa la Clave de licitación', 'maxlength' => '80']) }}
            </div>
            <div class="col-3">
                {{ Form::label('Descripcion', 'Código de Barras', ['class' => '']) }}
                {{ Form::text('Descripcion', null, ['class' => 'form-control form-control-sm', 'required', 'placeholder'=>'Ingresa el código de barras', 'maxlength' => '80']) }}
            </div>
            <div class="col-3">
                {{ Form::label('Descripcion', 'Código SAT', ['class' => '']) }}
                {{ Form::text('Descripcion', null, ['class' => 'form-control form-control-sm', 'required', 'placeholder'=>'Ingresa el código SAT', 'maxlength' => '80']) }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-12">
                {{ Form::label('Clave Nemotécnica', 'Descripción Corta', ['class' => '']) }}
                {{ Form::text('Descrip1', null, ['class' => 'form-control form-control-sm', 'required', 'placeholder'=>'Descripción Corta', 'maxlength' => '80']) }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-12">
                {{ Form::label('Clave Nemotécnica', 'Descripción Larga', ['class' => '']) }}
                {{ Form::textarea('Descrip2', null, ['class' => 'form-control form-control-sm', 'style'=>'height:70px', 'required', 'placeholder'=>'Descripción Larga','maxlength' => '300']) }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-6">
                {{ Form::label('supplier1', 'Proveedor 1', ['class' => '']) }}
                {{ Form::select('supplier1', array('L' => 'Large', 'S' => 'Small'), null, ['class' => 'form-control form-control-sm', 'required']) }}
            </div>
            <div class="col-6">
                {{ Form::label('supplier2', 'Proveedor 2', ['class' => '']) }}
                {{ Form::select('supplier2', array('L' => 'Large', 'S' => 'Small'), null, ['class' => 'form-control form-control-sm', 'required']) }}
            </div>
        </div>
        <div class="form-row">
            <div class="col">
                {{ Form::label('needs_diary', 'Inventariable', ['class' => '']) }}
                {{ Form::checkbox('Inventaria', 1, null, ['class' => 'form-control form-control-sm']) }}
            </div>
            <div class="col">
                {{ Form::label('turn_service', 'En lista de precios', ['class' => '']) }}
                {{ Form::checkbox('turn_service', 1, null, ['class' => 'form-control form-control-sm']) }}
            </div>

            <div class="col">
                {{ Form::label('hour_service', 'Aplica Lote y Caducidad', ['class' => '']) }}
                {{ Form::checkbox('hour_service', 1, null, ['class' => 'form-control form-control-sm']) }}
            </div>

            <div class="col">
                {{ Form::label('event_service', 'Activo', ['class' => '']) }}
                {{ Form::checkbox('event_service', 1, null, ['class' => 'form-control form-control-sm']) }}
            </div>
            <div class="col">
                {{ Form::label('event_service', 'E-commerce', ['class' => '']) }}
                {{ Form::checkbox('event_service', 1, null, ['class' => 'form-control form-control-sm']) }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-12">
                {{ Form::label('Clave Nemotécnica', 'Observaciones', ['class' => '']) }}
                {{ Form::textarea('Observa', null, ['class' => 'form-control form-control-sm', 'style'=>'height:100px', 'placeholder'=>'Observaciones', 'required', 'maxlength' => '100']) }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-12">
                {{ Form::label('Clave Nemotécnica', 'Registro Salubridad', ['class' => '']) }}
                {{ Form::text('Descripcion', null, ['class' => 'form-control form-control-sm', 'placeholder'=>'Registro salubridad', 'required', 'maxlength' => '80']) }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-2">
                {{ Form::label('Clave Nemotécnica', 'IVA', ['class' => '']) }}
                {{ Form::text('IVA', null, ['class' => 'form-control form-control-sm', 'required', 'placeholder'=>'%', 'maxlength' => '80']) }}
            </div>
            <div class="col-2">
                {{ Form::label('Clave Nemotécnica', 'Utilidad Mínima Licitación', ['class' => '']) }}
                {{ Form::text('Descripcion', null, ['class' => 'form-control form-control-sm', 'required', 'placeholder'=>'%', 'maxlength' => '80']) }}
            </div>
            <div class="col-2">
                {{ Form::label('Clave Nemotécnica', 'Flete', ['class' => '']) }}
                {{ Form::text('Descripcion', null, ['class' => 'form-control form-control-sm', 'required', 'placeholder'=>'$', 'maxlength' => '80']) }}
            </div>
            <div class="col-2">
                {{ Form::label('Clave Nemotécnica', 'T Surtido', ['class' => '']) }}
                {{ Form::text('Descripcion', null, ['class' => 'form-control form-control-sm', 'required', 'placeholder'=>'Días', 'maxlength' => '80']) }}
            </div>
        </div>
        
        <div class="mt-3 mb-3" style="text-align: center">
            <button type="submit" class="btn btn-success btn-flat">
                <i class="fas fa-save"></i> Guardar
            </button>
            <a class="btn btn-danger btn-flat" href="{{ url()->route('rules-configurator.index') }}">
                <i class="fas fa-ban"></i> Cancelar
            </a>
        </div>
    {{ Form::close() }}

resources/views/products/partials/status.blade.php
@php
    list($title, $icon, $color) = ($product->Activo == 1) ? ['Activo', 'check-square', '#38c172'] : ['Inactivado', 'square', '#343a40'];
@endphp

<i class="fa fa-{{ $icon }}" title="{{ $title }}" aria-hidden="true" style="color: {{ $color }}"></i>
{{ $title }}

resources/views/products/partials/storageForm.blade.php
@includeIf('alerts.errors')
{{ Form::open(['route' => 'rules-configurator.store', 'method' => 'POST', 'class' => 'animated bounceInDown']) }}    
    <div class="form-row">
        <div class="col-3">
            {{ Form::label('supplier1', 'Nivel', ['class' => '']) }}
            {{ Form::select('category', array('L' => 'Large', 'S' => 'Small'), null, ['class' => 'form-control form-control-sm', 'style'=>'width:10px', 'required']) }}
        </div>
        <div class="col-3">
            {{ Form::label('supplier2', 'Empaque', ['class' => '']) }}
            {{ Form::select('supplier2', array('L' => 'Large', 'S' => 'Small'), null, ['class' => 'form-control form-control-sm', 'required']) }}
        </div>
        <div class="col-3">
            {{ Form::label('Clave Nemotécnica', 'Unidades', ['class' => '']) }}
            {{ Form::number('Descrip2', null, ['class' => 'form-control form-control-sm', 'required', 'placeholder'=>'Descripción Larga']) }}
        </div>
        <div class="col-3">
            {{ Form::label('supplier2', 'Nivel Compra', ['class' => '']) }}
            {{ Form::select('supplier2', array('L' => 'Large', 'S' => 'Small'), null, ['class' => 'form-control form-control-sm', 'required']) }}
        </div>
    </div>
    
    <div class="mt-3 mb-3" style="text-align: center">
        <button type="submit" class="btn btn-success btn-flat">
            <i class="fas fa-save"></i> Guardar
        </button>
        <a class="btn btn-danger btn-flat" href="{{ url()->route('rules-configurator.index') }}">
            <i class="fas fa-ban"></i> Cancelar
        </a>
    </div>
{{ Form::close() }}