routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Api\ShippingConfiguration\Box\BoxController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('login', [HomeController::class, 'index']);
Route::get('/', function(){
    return view('home');
})->middleware('auth');

Auth::routes();

Route::middleware(['auth'])->group(function () {

    Route::get('/shippings-config-user','ShippingConfigController@shippingsConfigUser');

    Route::resource('/shippings-config','ShippingConfigController')->only(['index','store','update','destroy']);
    //Route::resource('configurations', 'ConfigurationController',['only' => ['update','index']]);

    /*
    * Configuration Special Prices Routes
    */
    Route::name('special_prices.')->group(function () {
        Route::get('/special_prices', [App\Http\Controllers\SpecialPricesController::class, 'index'])->name('index');
        Route::post('/special_prices/show', [App\Http\Controllers\SpecialPricesController::class, 'show'])->name('show');
        Route::post('/special_prices/store', [App\Http\Controllers\SpecialPricesController::class, 'store'])->name('store');
        Route::get('/special_prices/create', [App\Http\Controllers\SpecialPricesController::class, 'create'])->name('create');
        Route::post('/special_prices/delete', [App\Http\Controllers\SpecialPricesController::class, 'delete'])->name('delete');
        Route::post('/special_prices/destroy', [App\Http\Controllers\SpecialPricesController::class, 'destroy'])->name('destroy');
        Route::post('/special_prices/search', [App\Http\Controllers\SpecialPricesController::class, 'searchProducts'])->name('search');
    });

    /*Base prices Routes
    *
    */
    Route::name('base-prices.')->group(function () {
        Route::get('/base-prices', [App\Http\Controllers\BasePriceController::class, 'index'])->name('index');
    });

    Route::resource('rules-configurator', 'RuleConfiguratorController', [
        'parameters' => [
            'rules-configurator' => 'rule'
        ],
        'except' => [
            'show'
        ]
    ]);

    Route::resource('global-costs-configurator', 'GlobalCostConfiguratorController', [
        'parameters' => [
            'global-costs-configurator' => 'cost'
        ],
        'except' => [
            'show'
        ]
    ]);

    Route::resource('global-utility', 'GlobalUtilityController', [
        'parameters' => [
            'global-utility' => 'cost'
        ],
        'only' => [
            'index',
            'update'
        ]
    ]);
    
    
    Route::resource('box', 'BoxController', [
        'except' => [
            'show'
        ]
    ]);

    Route::resource('products', 'ProductController', [
        'except' => [
            'index'
        ]
    ]);

});


Route::get('{any}', [HomeController::class, 'index'])->where('any', '.*');

resources/views/global_costs_configurator/partials/buttons.blade.php
@permission('*global_costs_configurator')
<div class="btn-group dropleft">
    <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Opciones
    </button>
    <div class="dropdown-menu">
        @permission('list_global_costs_configurator')
            <a class="dropdown-item" data-cost="{{ json_encode($cost) }}" onclick="window.fillMdl(this)" href="#"
               data-toggle="modal" data-target="#show-modal">
                Detalles
            </a>
        @endpermission
        @permission('edit_global_costs_configurator')
            <a href="{{ route('global-costs-configurator.edit', $cost->Id_ConceptoCosto) }}" class="dropdown-item">
                Editar
            </a>
        @endpermission
        @permission('delete_global_costs_configurator')
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" onclick="_global.toggleStatus('{{ route('global-costs-configurator.destroy', $cost->Id_ConceptoCosto) }}')" href="#">
                Cambiar estatus
            </a>
        @endpermission
    </div>
</div>
@endpermission

resources/views/global_costs_configurator/partials/inputs.blade.php
<div class="form-row">
    <div class="col-12">
        {{ Form::label('Descripcion', 'Descripción:', ['class' => '']) }}
        {{ Form::text('Descripcion', null, ['class' => 'form-control form-control-sm', 'required', 'maxlength' => '191']) }}
    </div>
</div>

<div class="form-row">
    <div class="col-12">
        {{ Form::label('type', 'Tipo:', ['class' => '']) }}
        <span style="color:red; font-weight: bold;" title="requerido">*</span> <br>

        <div class="form-check form-check-inline">
            {{ Form::radio('Tipo', 'P', ['checked']) }}
            <label class="form-check-label" for="Porcentaje">&nbsp;Porcentaje</label>
        </div>

        <div class="form-check form-check-inline">
            {{ Form::radio('Tipo', 'M') }}
            <label class="form-check-label" for="Monto">&nbsp;Monto</label>
        </div>

        <div class="form-check form-check-inline">
            {{ Form::radio('Tipo', 'C') }}
            <label class="form-check-label" for="Calculado">&nbsp;Calculado</label>
        </div>

    </div>
</div>

<div class="form-row">
    <div id="div-porcentaje" class="col-lg-6 col-md-12 col-sm-12 col-xs-12" style="display: none;">
        {{ Form::label('Porcentaje', 'Porcentaje:', ['class' => '']) }}
        {{ Form::number('Porcentaje', null, ['id' => 'inputPorcentaje', 'class' => 'form-control form-control-sm', 'required', 'min' => '0', 'step' => "0.01"]) }}
    </div>
</div>

<div class="form-row">
    <div id="div-monto" class="col-lg-6 col-md-12 col-sm-12 col-xs-12" style="display: none;">
        {{ Form::label('Monto', 'Monto:', ['class' => '']) }}
        {{ Form::number('Monto', null, ['id' => 'inputMonto', 'class' => 'form-control form-control-sm', 'required', 'min' => '0', 'step' => "0.01"]) }}
    </div>
    <div id="div-base-calculo" class="col-lg-6 col-md-12 col-sm-12 col-xs-12" style="display: none;">
        {{ Form::label('Id_BaseCostoCalculado', 'Base de Cálculo:', ['class' => '']) }}
        {{ Form::select('Id_BaseCostoCalculado', $bases, null, ['placeholder' => 'Seleccione una opción', 'class' => 'form-control form-control-sm', 'required', 'id' => 'inputBase']) }}
    </div>
</div>

resources/views/global_costs_configurator/partials/show.blade.php
<div class="modal fade" id="show-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Detalles</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row mdl-groups">
                    <div class="form-group col-md-6 col-sm-12">
                        {!! Form::labelMdl('Descripcion', 'Descripcion') !!}
                    </div>
                    <div class="form-group col-md-6 col-sm-12">
                        {!! Form::labelMdl('Tipo', 'Tipo') !!}
                    </div>
                </div>
                <div class="row mdl-groups">
                    <div class="form-group col-md-6 col-sm-12">
                        {!! Form::labelMdl('Porcentaje', 'Porcentaje') !!}
                    </div>
                    <div class="form-group col-md-6 col-sm-12">
                        {!! Form::labelMdl('Monto', 'Monto') !!}
                    </div>
                </div>
                <div class="row mdl-groups">
                    <div class="form-group col-md-6 col-sm-12">
                        {!! Form::labelMdl('Estatus', 'Estatus') !!}
                    </div>
                    <div class="form-group col-md-6 col-sm-12">
                        <small class="label-form">Base de Cálculo:</small>
                        {{ Form::select('BaseCalculo', $bases, null, ['placeholder' => 'Seleccione una opción', 'class' => 'form-control', 'id' => 'Id_BaseCostoCalculado', 'disabled']) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/global_costs_configurator/partials/status.blade.php
@php
    list($title, $icon, $color) = ($cost->Estatus) ? ['Activado', 'check-square', '#38c172'] : ['Desactivado', 'square', '#343a40'];
@endphp

<i class="fa fa-{{ $icon }}" title="{{ $title }}" aria-hidden="true" style="color: {{ $color }}"></i>
{{ $title }}